export const LAY_CHI_TIET_PHONG_VE = 'LAY_CHI_TIET_PHONG_VE'
export const CHON_GHE = 'CHON_GHE'
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT'
export const CHUYEN_TAB_HOAN_TAT = "CHUYEN_TAB_HOAN_TAT"
export const CHUYEN_TAB_DAT_VE = "CHUYEN_TAB_DAT_VE"